lang: "ja"
title: takapiro99 のページ
# description: 北海道大学の学生を中心とした IT 系学生サークルです
theme: jekyll-theme-slate
exclude:
  - "docker-compose.yml"
  - "README.md"
permalink: /:year/:title
twitter:
  username: takapiro_99
  card: summary_large_image
# logo: /huit_logo_white.png
future: true
locale: ja_JP