version: "3"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    command: jekyll serve --force_polling
    volumes:
      - ./:/srv/jekyll
    ports:
      - 4000:4000